### ISSUE TITLE
JSON description of form should comply with and validate against a schema

### ISSUE THREAD

**Issue by quietlyconfident** [SelmanKahya/angularjs-form-builder#16]
## Definitions
- **Form Schema** _(AKA "Schema")_ A [JSON Schema](http://json-schema.org/) document which describes a form (e.g. a Contact Name & Address Form), and which the data of that form could be validated against.
- **Form Schema Specification**  _(AKA "Spec")_ - A [JSON Schema](http://json-schema.org/) document which can be used to validate a Form Schema.
## Issues
1. **Form Schema should be a JSON Schema against which the form's data could be validated using a standard validator.**  Right now, this project builds a **Form Schema** (e.g. the JSON description of the form at the bottom of the editor), but it is not a JSON Schema compliant schema.  Thus server side or other more advanced validation is difficult to implement.  This other project, [angular-schema-form](https://github.com/Textalk/angular-schema-form), creates the form from the schema and also validates the form fields against the same schema; and it is a JSON Schema schema.
2. There should be a **Form Schema Specification** against which a Schema can be validated, and which simultaneously could be used by Angularjs-form-builder to configure the options available to the form builder; and the **Form Schema Specification** should be a JSON Schema schema.  Right now, the reference / standard for what fields are available in the program is the code itself.  For example, field-directive.js , form-service.js, etc.  And, given a Form Schema (e.g. the JSON Description of the form at the bottom of the builder page) there is no way to validate that the object is valid - it could have a typo, or request an invalid widget / field, etc.

If these two issues were implemented, a few very cool things become true. . . First, other programs could use the output of Angularjs-form-builder (e.g. a Form Schema generated by a user) by implementing the fields / widgets / etc. defined by the Form Schema Specification.  Second, users could potentially add additional field types / options / etc. more easily without forking the code; simply by using their copy of the code with a different form schema specification.  For example, perhaps a user wanted to permit only true/false questions to be built using the application.  They could remove the other permitted fields from the spec.

**Comment by SelmanKahya** [comment]
project isn't maintained anymore, thanks.
