### ISSUE TITLE
publish a version @ bower repository

### ISSUE THREAD

**Issue by lgazo** [SelmanKahya/angularjs-form-builder#17]
Hi,

would it by possible to publish a version that can be available via bower directly without the need to build it on my own?

Thank you.

**Comment by Selmanh** [comment]
I am not clear on this. The form builder is not a library, there is no single js file that users can import and extend their app's functionality. Why should we create a bower package?

**Comment by SelmanKahya** [comment]
project isn't maintained anymore, thanks.
