### ISSUE TITLE
Json data 

### ISSUE THREAD

**Issue by ambinabhi** [SelmanKahya/angularjs-form-builder#20]
When i open the forms page, the whole json file is displayed for 2-3 secs and after that form is displayed. is it a quirk ?..or can i hide that json data. any help would be much appreciated.

**Comment by Selmanh** [comment]
Yea, I remember trying to use ngCloak but it didn't work. Maybe there is something we can use in the newer versions?

**Comment by aaron-straker** [comment]
I was able to fix the temporary flash of the json object during the initial load by replacing:
    `<div>{{field}}</div>` with `<div ng-bind="field"></div>` in the field-directive.js file's return object. Hopefully this helps you out also.

**Comment by Selmanh** [comment]
would you like to send a PR? :heart_eyes:

**Comment by aaron-straker** [comment]
Sent.

**Comment by SelmanKahya** [comment]
project isn't maintained anymore, thanks.
