### ISSUE TITLE
AngularJS v1.4.5 gives error

### ISSUE THREAD

**Issue by bilal186** [SelmanKahya/angularjs-form-builder#27]
I am using this form builder with AngularJS v1.4.5 it gives me the following error Please suggest me the solution

Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.5/$injector/modulerr?p0=angularjsFormBuilde…orm-builder%2Fapp%2Fbower_components%2Fangular%2Fangular.min.js%3A40%3A435)

**Comment by bilal186** [comment]
Failed to instantiate module angularjsFormBuilderApp due to:
Error: [$injector:unpr] http://errors.angularjs.org/1.4.5/$injector/unpr?p0=%24ro...
https://docs.angularjs.org/error/$injector/unpr?p0=$routeProvider

**Comment by SelmanKahya** [comment]
project isn't maintained anymore, thanks.
